<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Tsikhanau.ValueObjects</PackageId>
        <Version>1.0.0</Version>
        <Authors>Stsiapan Tsikhanau</Authors>
        <Description>Core building blocks</Description>
        <IncludeBuildOutput>true</IncludeBuildOutput>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Tsikhanau.Packages.ValueObjects</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Collection\" />
      <Folder Include="Integer\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tsikhanau.Outcomes\Tsikhanau.Outcomes.csproj" />
    </ItemGroup>

</Project>
