<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Xunit" />
        <Using Include="Shouldly" />
        <Using Include="NSubstitute" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="xunit.v3.mtp-v2" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="NSubstitute" />
        <PackageReference Include="NSubstitute.Analyzers.CSharp" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Tsikhanau.Railway.AspNetCore\Tsikhanau.Railway.AspNetCore.csproj" />
    </ItemGroup>

</Project>
