<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tsikhanau.Outcomes\Tsikhanau.Outcomes.csproj" />
      <ProjectReference Include="..\Tsikhanau.Flow\Tsikhanau.Flow.csproj" />
      <ProjectReference Include="..\Tsikhanau.ValueObjects\Tsikhanau.ValueObjects.csproj" />
      <ProjectReference Include="..\Tsikhanau.RailwayExtensions\Tsikhanau.RailwayExtensions.csproj" />
      <ProjectReference Include="..\Tsikhanau.Validation\Tsikhanau.Validation.csproj" />
    </ItemGroup>


</Project>
