<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Tsikhanau.Outcomes</PackageId>
        <Version>1.0.1</Version>
        <Authors>Stsiapan Tsikhanau</Authors>
        <Description>Core building blocks</Description>
        <IncludeBuildOutput>true</IncludeBuildOutput>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Either\" />
      <Folder Include="Optional\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Tsikhanau.Foundation\Tsikhanau.Foundation.csproj" />
    </ItemGroup>

</Project>
